# Generated by Django 4.1.5 on 2023-01-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_menuitem_alter_ingredient_id_menuitemrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(default='cocktail', max_length=50),
        ),
    ]
