# Generated by Django 4.1.5 on 2023-01-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_menuitem_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemrequirement',
            name='ingredient_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
