# Generated by Django 4.1.5 on 2023-01-30 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemrequirement',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ingredient'),
        ),
        migrations.AlterField(
            model_name='menuitemrequirement',
            name='menu_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.menuitem'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 30)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='menu_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.menuitem'),
        ),
    ]
