# Generated by Django 4.1.5 on 2023-01-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_menuitemrequirement_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemrequirement',
            name='ingredient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ingredient'),
        ),
        migrations.AlterField(
            model_name='menuitemrequirement',
            name='menu_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.menuitem'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='menu_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.menuitem'),
        ),
    ]
